# Generated by Django 4.2.5 on 2023-09-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdatapoint',
            old_name='precipitation',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='weatherdatapoint',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='weatherdatapoint',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='weatherdatapoint',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='weatherdatapoint',
            name='wind',
        ),
    ]
